[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.0"
reqwest = { version="0.11.13", features = ["blocking"] }
regex = "1.7.0"
rayon = "1.6.1"
ahash = "0.8.2"
anyhow = "1.0.75"
